apiVersion: v1
data:
  filebeat.yml: "filebeat.autodiscover:\n  providers:\n    - type: kubernetes\n      templates:\n
    \       - condition:\n            not:\n              equals:\n                kubernetes.annotations.json_logs:
    false\n    - type: kubernetes\n      node: ${NODE_NAME}\n      hints.enabled:
    true\n      hints.default_config:\n        type: container\n        paths:\n          -
    /var/log/containers/*${data.kubernetes.container.id}.log                  \nprocessors:\n
    \ - decode_json_fields:\n      fields: [\"message\"]\n      target: \"json_message\"\n
    \     process_array: true\n      max_depth: 10\n      overwrite_keys: false\n
    \ - add_fields:\n      target: 'kubernetes'\n      fields:\n        cluster.name:
    ose-lab\noutput.logstash:\n  hosts: [\"elk-7pstash700.dev.mtb.com:5048\"]\n  loadbalance:
    false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"filebeat.yml":"filebeat.autodiscover:\n  providers:\n    - type: kubernetes\n      templates:\n        - condition:\n            not:\n              equals:\n                kubernetes.annotations.json_logs: false\n    - type: kubernetes\n      node: ${NODE_NAME}\n      hints.enabled: true\n      hints.default_config:\n        type: container\n        paths:\n          - /var/log/containers/*${data.kubernetes.container.id}.log                  \nprocessors:\n  - decode_json_fields:\n      fields: [\"message\"]\n      target: \"json_message\"\n      process_array: true\n      max_depth: 10\n      overwrite_keys: false\n  - add_fields:\n      target: 'kubernetes'\n      fields:\n        cluster.name: ose-lab\noutput.logstash:\n  hosts: [\"elk-7pstash700.dev.mtb.com:5048\"]\n  loadbalance: false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"k8s-app":"filebeat"},"name":"filebeat-config","namespace":"filebeat"}}
  creationTimestamp: "2024-04-11T20:22:16Z"
  labels:
    k8s-app: filebeat
  name: filebeat-config
  namespace: filebeat
  resourceVersion: "113401"
  uid: 58e78913-866a-4966-94c5-717298e71f25
